### Registrar pedido
POST https://glowing-space-spoon-r4w7j9p5jq6r2wjjj-8080.app.github.dev/pedido/nuevo
Content-Type: application/json

{
 "items":[
   {
     "idProducto": 1023,
     "cantidad": 20,
     "precioUnitario":3000
   }
 ]
}


### Registrar producto
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/marca/1001/nuevo
Content-Type: application/json

{
 "nombre":"Nicolas",
"descripcion": "Franco Nicolas Rojas Castro",
	"precio":600,
	"stock":3
}


### Ajustar stock
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/stock/ajuste
Content-Type: application/json

{
  "idProducto": 1004,
  "stock": 4
}

### Consultar producto por id
GET https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/producto/1007

### Registrar pedido
POST https://humble-space-computing-machine-q7pxjppw65xph46jp-8080.app.github.dev/pedido/nuevo
Content-Type: application/json

{
 "items":[
   {
     "idProducto": 1004,
     "cantidad": 2,
     "precioUnitario":3000
   }
 ]
}


### Registrar producto
-----------------------------------------------------------------------
JSON='
{
 "items":[
   {
     "idProducto": 1004,
     "cantidad": 2,
     "precioUnitario":3000
   }
 ]
}'